### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by bpbond** [JGCRI/JGCRIutils#1]
As @rplzzz noted on Slack, one obvious functionality `JGCRIutils` could provide would be logging. There are existing packages that do this, although I personally find most of them overly complex and cumbersome.

**Comment by bpbond** [comment]
My basic logging function looks like this:

```R
# -----------------------------------------------------------------------------
# Time-stamped output function
printlog <- function(msg="", ..., ts = TRUE, cr = TRUE) {
  if(ts) cat(date(), " ")
  cat(msg, ...)
  if(cr) cat("\n")
} # printlog
```

Every script basically looks like this:

```R
openlog(SCRIPTNAME)

# ... script ....
printlog("Writing output file...")
# ... script ....

closelog()   # write sessionInfo() and close log
```

producing a log file `./output/SCRIPTNAME/SCRIPTNAME.log` like this

```
Mon Sep 14 06:29:39 2015  Welcome to 1-data.R
Mon Sep 14 06:29:39 2015  Data directory is data/picarro/
Mon Sep 14 06:29:39 2015  Reading data/picarro//CFADS2283-20150831-171845Z-DataLog_User.dat.gz
Mon Sep 14 06:29:39 2015  d rows = 2679 cols = 17
Mon Sep 14 06:29:44 2015  Writing output file...
Mon Sep 14 06:29:44 2015  Saving outputs//rawdata.csv [gzip]
Mon Sep 14 06:29:47 2015  All done with 1-data.R
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)
```

**Comment by rplzzz** [comment]
We should add a logging level  as an optional parameter so that we can readily adjust the amount of output up or down.

**Comment by bpbond** [comment]
Agreed, an obvious improvement. I'll code this up and commit to repo.

**Comment by bpbond** [comment]
OK, see committed code (d38b83e). This provides three user-accessible functions, `openlog()`, `printlog()`, and `closelog()`. Features:

* Logs and messages can have priority levels. Messages only appear in a log when their level exceeds that of the log.
* Can specify a custom logfile.
* Can append to an already-existing logfile.
* Can `sink`, capturing ALL screen output to a logfile.

For example:
```R
> library(JGCRIutils)
> openlog("test")
Wed Sep 16 12:31:03 2015  Opening ./output//test/test.log.txt
> printlog("Message", 1, 2, 3)
Wed Sep 16 12:31:15 2015  Message 1 2 3
> print("sink is on by default, so this will also appear")
[1] "sink is on by default, so this will also appear"
> closelog()
Wed Sep 16 12:31:19 2015  Closing ./output//test/test.log.txt
```

**Comment by bpbond** [comment]
Note that I'm using a hidden variable in the global environment to store logging info. This isn't perfect, as there's a chance someone else will also be using a `.loginfo`...

**Comment by rplzzz** [comment]
Do packages have namespaces associated with them?  If so, then when we convert this into a package we can change the global symbol to package-level.

**Comment by bpbond** [comment]
Yeah, that's a better solution, thanks. Will do.

On another note - I just added (84e6b02) some test code to ensure logging functions behave as intended.

**Comment by bpbond** [comment]
Closing this. If (when) we find bugs w/ logging code, or want new features, new issues can be opened.
